<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="SBHModel" nsURI="SBHModel.storagebenchmarkharness.sdq.kit.edu"
    nsPrefix="SBH">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfSut">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileSystem" eType="#//FileSystem"
        defaultValueLiteral="null" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheduler" eType="#//Scheduler"
        defaultValueLiteral="null"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfBenchmark" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfFFSB" eSuperTypes="#//IndependentVariablesOfBenchmark">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readPercentage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeBlockSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="readBlockSize" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequentialAccess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequentialRead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequentialWrite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeFsync" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threadCount" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="warmUpTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opsPerFile" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directIO" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opsPerFileRead" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opsPerFileWrite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opDelay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfPostmark" eSuperTypes="#//IndependentVariablesOfBenchmark">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FileSystem">
    <eLiterals name="ext4" value="1" literal="ext4"/>
    <eLiterals name="XFS" value="2"/>
    <eLiterals name="BTRFS" value="3" literal="BTRFS"/>
    <eLiterals name="ext3" value="4" literal="ext3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Scheduler">
    <eLiterals name="NOOP" value="1"/>
    <eLiterals name="CFQ"/>
    <eLiterals name="DEADLINE"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfFilebench" eSuperTypes="#//IndependentVariablesOfBenchmark">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="threads" lowerBound="1"
        upperBound="-1" eType="#//Thread"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filesets" lowerBound="1"
        upperBound="-1" eType="#//Fileset"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="warmupTime" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="File" instanceClassName="java.io.File"/>
  <eClassifiers xsi:type="ecore:EClass" name="Thread">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threadName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="memsize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" lowerBound="1"
        upperBound="-1" eType="#//Operations/Operation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instances" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Fileset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="directory" lowerBound="1"
        eType="#//File"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="meanDirWidth" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="files" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="meanFileSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="prealloc" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfMonitor" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfBlktrace" eSuperTypes="#//IndependentVariablesOfMonitor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="bufferSize numberOfBuffers"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
      <details key="bufferSize" value="bufferSize>=0 and bufferSize&lt;=9999"/>
      <details key="numberOfBuffers" value="numberOfBuffers>=0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bufferSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfBuffers" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetDevice" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="logFilePrefix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="avgRequestSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestMix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessPattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visualizeAccessPattern"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternWindowSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opsPerFile" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opsWindowSize" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordQ2c" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="activeQueueDepth" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependentVariables">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benchmarkPrefix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="values" ordered="false"
        unique="false" upperBound="-1" eType="#//DependentVariablesValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Timestamp" instanceClassName="java.sql.Timestamp"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Metric">
    <eLiterals name="responseTime"/>
    <eLiterals name="throughput" value="1" literal="throughput"/>
    <eLiterals name="operations" value="2" literal="operations"/>
    <eLiterals name="requestSize" value="3"/>
    <eLiterals name="access" value="4" literal="access"/>
    <eLiterals name="requestMix" value="5"/>
    <eLiterals name="filesetSize" value="6" literal="filesetSize"/>
    <eLiterals name="filesize" value="7" literal="filesize"/>
    <eLiterals name="threads" value="8"/>
    <eLiterals name="opsPerFile" value="9" literal="opsPerFile"/>
    <eLiterals name="queueDepth" value="10" literal="10"/>
    <eLiterals name="mergesPerSec" value="11" literal="mergesPerSec"/>
    <eLiterals name="serviceTime" value="12" literal="serviceTime"/>
    <eLiterals name="cpuUtilUser" value="13"/>
    <eLiterals name="cpuUtilNice" value="14" literal="cpuUtilNice"/>
    <eLiterals name="cpuUtilSystem" value="15"/>
    <eLiterals name="cpuIowait" value="16"/>
    <eLiterals name="cpuSteal" value="17"/>
    <eLiterals name="cpuIdle" value="18" literal="cpuIdle"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependentVariablesValue" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationMetric" lowerBound="1"
        eType="#//Metric"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependentVariablesValueSingle" eSuperTypes="#//DependentVariablesValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="timestamp" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DependentVariablesValueComposite" eSuperTypes="#//DependentVariablesValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="mean"/>
    <eLiterals name="stdDev" value="1"/>
    <eLiterals name="absolute" value="2" literal="absolute"/>
    <eLiterals name="pattern" value="3"/>
    <eLiterals name="relation" value="4"/>
    <eLiterals name="singleValue" value="6" literal="singleValue"/>
    <eLiterals name="percentage" value="5" literal="percentage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfFilesetMonitor"
      eSuperTypes="#//IndependentVariablesOfMonitor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="bufferSize numberOfBuffers"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfFilesizeMonitor"
      eSuperTypes="#//IndependentVariablesOfMonitor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="bufferSize numberOfBuffers"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfThreadsMonitor"
      eSuperTypes="#//IndependentVariablesOfMonitor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="bufferSize numberOfBuffers"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="benchmarkPrefix" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfIostatMonitor"
      eSuperTypes="#//IndependentVariablesOfMonitor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetDevice" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eSubpackages name="Configuration" nsURI="Configuration.SBHModel.storagebenchmarkharness.sdq.kit.edu"
      nsPrefix="SBHC">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Configuration">
      <eStructuralFeatures xsi:type="ecore:EReference" name="experimentSetup" eType="#//Configuration/ExperimentSetup"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="systemUnderTestRepository"
          eType="#//Configuration/SystemUnderTestRepository" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="independentVariableSpaceRepository"
          eType="#//Configuration/IndependentVariableSpaceRepository" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemUnderTest">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="identifierNotEmpty" value="identifier.size()>0"/>
        <details key="ipNotEmpty" value="ip.size()>0"/>
        <details key="userNotEmpty" value="user.size()>0"/>
        <details key="keyFileNotEmpty" value="keyFile.size()>0"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="identifierNotEmpty ipNotEmpty userNotEmpty keyFileNotEmpty"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="ip" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="port" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="22"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyFile" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariableSpaceOfSut" eSuperTypes="#//Configuration/IndependentVariableSpace">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileSystem" lowerBound="1"
          upperBound="-1" eType="#//FileSystem"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheduler" lowerBound="1"
          upperBound="-1" eType="#//Scheduler"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariableSpaceOfBenchmark"
        abstract="true" eSuperTypes="#//Configuration/IndependentVariableSpace">
      <eTypeParameters name="Experiment">
        <eBounds eClassifier="#//IndependentVariablesOfBenchmark"/>
      </eTypeParameters>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariableSpaceOfFFSB">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="readBlockSizeGtZ writeBlockSizeGtZ readPercentageBounds atLeastOne blockSizes sequentialAccesses opsPerFile&#xA;&#xA;"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="readBlockSizeGtZ" value="readBlockSize->any(v|v&lt;=0)->size()=0 or readPercentage->any(v|v>0)->size()=0"/>
        <details key="writeBlockSizeGtZ" value="writeBlockSize->any(v|v&lt;=0)->size()=0 or readPercentage->any(v|v&lt;100)->size()=0"/>
        <details key="readPercentageBounds" value="readPercentage->any(v|v&lt;0 or v>100)->size()=0"/>
        <details key="atLeastOne" value="readPercentage->size()>0 and&#xA;filesetSize->size()>0 and&#xA;writeFsync->size()>0 and&#xA;threadCount->size()>0 and&#xA;runTime->size()>0 and&#xA;warmUpTime->size()>0 and&#xA;fileSize->size()>0 and&#xA;directIO->size()>0&#xA;"/>
        <details key="sequentialAccesses" value="((sequentialRead->size()=0) = (sequentialWrite->size()=0)) and&#xA;(sequentialRead->size()>0 implies sequentialAccess->size()=0) and&#xA;(sequentialAccess->size()>0 implies sequentialRead->size()=0)"/>
        <details key="blockSizes" value="(readBlockSize->size() = writeBlockSize->size()) and&#xA;(readBlockSize->size()>0 implies blockSize->size()=0) and&#xA;(blockSize->size()>0 implies readBlockSize->size()=0)"/>
        <details key="opsPerFile" value="(opsPerFileRead->size() = opsPerFileWrite->size()) and&#xA;(opsPerFileRead->size()>0 implies opsPerFile->size()=0) and&#xA;(opsPerFile->size()>0 implies opsPerFileRead->size()=0)"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="blockSize" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="readBlockSize" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeBlockSize" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="readPercentage" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetSize" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequentialAccess" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequentialRead" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequentialWrite" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeFsync" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="threadCount" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="runTime" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="warmUpTime" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileSize" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opsPerFile" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directIO" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opsPerFileRead" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opsPerFileWrite" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opDelay" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      <eGenericSuperTypes eClassifier="#//Configuration/IndependentVariableSpaceOfBenchmark">
        <eTypeArguments eClassifier="#//IndependentVariablesOfFFSB"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariableSpaceOfPostmark">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="applicationName" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="#//Configuration/IndependentVariableSpaceOfBenchmark">
        <eTypeArguments eClassifier="#//IndependentVariablesOfPostmark"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariableSpace" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExperimentSeries">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="&#xA;"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="identifierNotEmpty" value="identifier.size()>0"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="independentVariableSpaceOfBenchmark"
          lowerBound="1">
        <eGenericType eClassifier="#//Configuration/IndependentVariableSpaceOfBenchmark">
          <eTypeArguments/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="independentVariableSpaceOfSut"
          lowerBound="1" eType="#//Configuration/IndependentVariableSpaceOfSut"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="IndependentVariablesOfMonitor"
          upperBound="-1">
        <eGenericType eClassifier="#//Configuration/IndependentVariablesOfMonitor">
          <eTypeArguments/>
        </eGenericType>
      </eStructuralFeatures>
      <eStructuralFeatures xsi:type="ecore:EReference" name="systemUnderTest" lowerBound="1"
          eType="#//Configuration/SystemUnderTest"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ExperimentSetup">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="identifierNotEmpty repeatCountGtZ"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="identifierNotEmpty" value="identifier.size()>0"/>
        <details key="repeatCountGtZ" value="repeatCount > 0"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="identifier" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          iD="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="experimentSeries" lowerBound="1"
          upperBound="-1" eType="#//Configuration/ExperimentSeries" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeatCount" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="repeatWarmup" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SystemUnderTestRepository">
      <eStructuralFeatures xsi:type="ecore:EReference" name="systemsUnderTest" upperBound="-1"
          eType="#//Configuration/SystemUnderTest" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariableSpaceRepository">
      <eStructuralFeatures xsi:type="ecore:EReference" name="independentVariableSpaces"
          upperBound="-1" eType="#//Configuration/IndependentVariableSpace" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariableSpaceOfFilebench">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="atLeastOne paramConsts"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="atLeastOne" value="runTime->size()>0"/>
        <details key="paramConsts" value="runTime->any(v|v&lt;=0)->size()=0"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EReference" name="threads" lowerBound="1"
          upperBound="-1" eType="#//Configuration/Thread" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="filesets" lowerBound="1"
          upperBound="-1" eType="#//Configuration/Fileset" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="runTime" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="filebench"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="warmupTime" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eGenericSuperTypes eClassifier="#//Configuration/IndependentVariableSpaceOfBenchmark">
        <eTypeArguments eClassifier="#//IndependentVariablesOfFilebench"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Thread">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="atLeastOne" value="runTime->size()>0 and&#xA;memsize->size()>0 and&#xA;instances->size()>0"/>
        <details key="paramConsts" value="memsize->any(v|v&lt;=0)->size()=0 or instances->any(v|v&lt;=0)->size()=0"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="memsize" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="operations" lowerBound="1"
          upperBound="-1" eType="#//Configuration/Operations/Operation" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="instances" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="threadName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="thread1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fileset">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="atLeastOne" value="directory->size()>0 and&#xA;meanDirWidth->size()>0 and&#xA;files->size()>0 and&#xA;meanFileSize->size()>0 and&#xA;prealloc->size()>0"/>
        <details key="paramConsts" value="directory->any(v|v&lt;=0)->size()=0 or meanDirWidth->any(v|v&lt;=0)->size()=0 or files->any(v|v&lt;=0)->size()=0 or meanFileSize->any(v|v&lt;=0)->size()=0 or prealloc->any(v|v&lt;=0)->size()=0"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directory" lowerBound="1"
          upperBound="-1" eType="#//File"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="meanDirWidth" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="files" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="meanFileSize" lowerBound="1"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="prealloc" lowerBound="1"
          upperBound="101" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="fileset1"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfMonitor" abstract="true"
        eSuperTypes="#//Configuration/IndependentVariableSpace">
      <eTypeParameters name="Experiment">
        <eBounds eClassifier="#//IndependentVariablesOfMonitor"/>
      </eTypeParameters>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfBlktrace">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="atLeastOne" value="directory->size()>0 and&#xA;meanDirWidth->size()>0 and&#xA;files->size()>0 and&#xA;meanFileSize->size()>0 and&#xA;prealloc->size()>0"/>
        <details key="paramConsts" value="directory->any(v|v&lt;=0)->size()=0 or meanDirWidth->any(v|v&lt;=0)->size()=0 or files->any(v|v&lt;=0)->size()=0 or meanFileSize->any(v|v&lt;=0)->size()=0 or prealloc->any(v|v&lt;=0)->size()=0"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bufferSize" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="numberOfBuffers" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetDevice" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="logFilePrefix" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="/"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="avgRequestSize" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="requestMix" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="accessPattern" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="visualizeAccessPattern"
          lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="false"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="patternWindowSize" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opsPerFile" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="opsWindowSize" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="-1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="recordQ2c" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="activeQueueDepth" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eGenericSuperTypes eClassifier="#//Configuration/IndependentVariablesOfMonitor">
        <eTypeArguments eClassifier="#//IndependentVariablesOfBlktrace"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfFilesetMonitor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
      <eGenericSuperTypes eClassifier="#//Configuration/IndependentVariablesOfMonitor">
        <eTypeArguments eClassifier="#//IndependentVariablesOfFilesetMonitor"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfFilesizeMonitor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
      <eGenericSuperTypes eClassifier="#//Configuration/IndependentVariablesOfMonitor">
        <eTypeArguments eClassifier="#//IndependentVariablesOfFilesizeMonitor"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependentVariablesOfThreadsMonitor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="benchmarkPrefix" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="#//Configuration/IndependentVariablesOfMonitor">
        <eTypeArguments eClassifier="#//IndependentVariablesOfThreadsMonitor"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="IndependetVariablesOfIostatMonitor">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="interval" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetDevice" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eGenericSuperTypes eClassifier="#//Configuration/IndependentVariablesOfMonitor">
        <eTypeArguments eClassifier="#//IndependentVariablesOfIostatMonitor"/>
      </eGenericSuperTypes>
    </eClassifiers>
    <eSubpackages name="Operations" nsURI="Operations.Configuration.SBHModel.storagebenchmarkharness.sdq.kit.edu"
        nsPrefix="SBHCO">
      <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationName" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="flowOpName" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="warmupOperation" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
            defaultValueLiteral="true"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Read" eSuperTypes="#//Configuration/Operations/Operation">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
          <details key="constraints" value="directio random"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
          <details key="directio" value="directio=0 or directio=1"/>
          <details key="random" value="random=0 or random=1"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="iosize" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="random" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="iters" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral="1"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CreateFile" eSuperTypes="#//Configuration/Operations/Operation">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
          <details key="constraints" value="directio"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
          <details key="directio" value="directio=0 or directio=1"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="WriteHoleFile" eSuperTypes="#//Configuration/Operations/Operation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="iosize" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="iters" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="workingset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="srcfd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="CloseFile" eSuperTypes="#//Configuration/Operations/Operation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="OpenFile" eSuperTypes="#//Configuration/Operations/Operation">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
          <details key="constraints" value="directio"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
          <details key="directio" value="directio=0 or directio=1"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="AppendFileRand" eSuperTypes="#//Configuration/Operations/Operation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="iosize" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="iters" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="workingset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="ReadWholeFile" eSuperTypes="#//Configuration/Operations/Operation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="iosize" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="iters" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral=""/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="DeleteFile" eSuperTypes="#//Configuration/Operations/Operation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="StatFile" eSuperTypes="#//Configuration/Operations/Operation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Fsync" eSuperTypes="#//Configuration/Operations/Operation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Write" eSuperTypes="#//Configuration/Operations/Operation">
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
          <details key="constraints" value="directio random"/>
        </eAnnotations>
        <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
          <details key="directio" value="directio=0 or directio=1"/>
          <details key="random" value="random=0 or random=1"/>
        </eAnnotations>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="iosize" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="random" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="iters" upperBound="-1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
            defaultValueLiteral="1"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" upperBound="2"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      </eClassifiers>
      <eClassifiers xsi:type="ecore:EClass" name="Delay" eSuperTypes="#//Configuration/Operations/Operation">
        <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
            eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      </eClassifiers>
    </eSubpackages>
  </eSubpackages>
  <eSubpackages name="Operations" nsURI="Operations.SBHModel.storagebenchmarkharness.sdq.kit.edu"
      nsPrefix="SBHO">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
      <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" interface="true">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operationName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="flowOpName" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="warmupOperation" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Read" eSuperTypes="#//Operations/Operation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="directio random"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="directio" value="directio=0 or directio=1"/>
        <details key="random" value="random=0 or random=1"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iosize" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="random" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iters" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CreateFile" eSuperTypes="#//Operations/Operation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="directio"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="directio" value="directio=0 or directio=1"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WriteHoleFile" eSuperTypes="#//Operations/Operation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iosize" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iters" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="workingset" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="srcfd" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CloseFile" eSuperTypes="#//Operations/Operation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OpenFile" eSuperTypes="#//Operations/Operation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="directio"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="directio" value="directio=0 or directio=1"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AppendFileRand" eSuperTypes="#//Operations/Operation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iosize" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iters" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="workingset" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ReadWholeFile" eSuperTypes="#//Operations/Operation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileset" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iosize" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iters" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral=""/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeleteFile" eSuperTypes="#//Operations/Operation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StatFile" eSuperTypes="#//Operations/Operation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Fsync" eSuperTypes="#//Operations/Operation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Write" eSuperTypes="#//Operations/Operation">
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
        <details key="constraints" value="directio random"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL">
        <details key="directio" value="directio=0 or directio=1"/>
        <details key="random" value="random=0 or random=1"/>
      </eAnnotations>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="filesetname" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iosize" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="directio" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="random" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="iters" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
          defaultValueLiteral="1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="fd" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="dsync" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Delay" eSuperTypes="#//Operations/Operation">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
