CREATE TABLE IF NOT EXISTS configurationRuns(crId INTEGER PRIMARY KEY, crIdentifier VARCHAR NOT NULL, crSynchronized BOOLEAN, crTime DATETIME NOT NULL, crFinished BOOLEAN);
CREATE TABLE IF NOT EXISTS runs(runId INTEGER PRIMARY KEY, crId INTEGER NOT NULL, repeatNo INTEGER NOT NULL, expNo INTEGER NOT NULL, hostId VARCHAR NOT NULL, benchmarkId VARCHAR NOT NULL, expUid VARCHAR NOT NULL);

CREATE INDEX IF NOT EXISTS runsCrId ON runs(crId);
CREATE INDEX IF NOT EXISTS runRepeatNo ON runs(repeatNo);
CREATE INDEX IF NOT EXISTS runsExpNo ON runs(expNo);
CREATE INDEX IF NOT EXISTS runsHostId ON runs(hostId);


